TEXT REPRESENTATION

In [ ]:
# 1 bag of words
# we use conivectoriztion

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({'text':['people wacth cricket','player was player',
                         'people write comment',
                         'cricket play comment'],'output':[1,1,0,0]})

In [ ]:
df

                   text  output
0  people wacth cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
# people watch cricket player was written comment play
# []
# []
# []
# []

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'wacth': 5, 'cricket': 1, 'player': 4, 'was': 6, 'write': 7, 'comment': 0, 'play': 3}

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 1 0 0]]
[[0 0 0 0 2 0 1 0]]

In [ ]:
cv.transform(['cricket watch and write comment of cricket comment']).toarray()

array([[2, 2, 0, 0, 0, 0, 0, 1]])

In [ ]:
# 2

In [ ]:
v=CountVectorizer(ngram_range=(1,2))
# v=CountVectorizer(ngram_range=(2,2))

In [ ]:
bow=v.fit_transform(df['text'])

In [ ]:
df['text']

0    people wacth cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [ ]:
print(v.vocabulary_)

{'people': 3, 'wacth': 10, 'cricket': 1, 'people wacth': 4, 'wacth cricket': 11, 'player': 8, 'was': 12, 'player was': 9, 'was player': 13, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

In [ ]:
# TF(Term Frequency)
# IDF(Inverse Document Frequency)

In [ ]:
# TF(t,d) = (number of occurences of term t in document s)/
# (Total number ofterms in the document d)
# example==>
# d1=people watch cricket.
# tf(people,d1)=1/3

# d1=match was match.
# tf(match,d1)=2/3

In [ ]:
#  IDF(t)=loge(toatal number of documents in the corpus)/
# (number of documents with term t in them)
# here corpus means  number of sentences

#example==>
# d1='people wacth cricket'
# d2='player was player'
# d3=people write comment
# d4='cricket play comment'
# Idf(cricket)=log(4/4)
# Idf(people)=log(4/2)

In [ ]:
# we can use this by apply feature_extraction method in sklearn

In [ ]:
df

                   text  output
0  people wacth cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.66767854, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.        , 0.4472136 , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'wacth' 'was' 'write']

In [ ]:
import pandas as pd
import re
import string
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv(
    "/content/IMDB Dataset - IMDB Dataset.csv",
    encoding='utf-8',
    engine='python',
    on_bad_lines='skip'
)

# Take top 50 rows
df = df.head(50)

In [ ]:
# -----------------------------------
# Text Cleaning Functions
# -----------------------------------

# Lowercase
df['review'] = df['review'].str.lower()

In [ ]:
# Remove HTML tags
import re
def remove_html_tags(text):
  Pattern=re.compile('<.*?>')
  return Pattern.sub(r'',text)

In [ ]:
text="<html><body><p> m=Movie1 </p> Click here to <a heref='http://goggle.com'>download/a"

In [ ]:
remove_html_tags(text)

' m=Movie1  Click here to download/a'

In [ ]:
df['review'] = df['review'].apply(remove_html_tags)

In [ ]:
# Remove URLs
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

In [ ]:
text4='for notebook click http://www.deture.com/delta/note1234acc'

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
# Remove punctuation
exclude = string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
    return text

In [ ]:
text3='string.with.punctuation?'

In [ ]:
remove_punc(text3)

'string.with.punctuation?'

In [ ]:
df['review']=df['review'].apply(remove_punc)

In [ ]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
5   probably my all-time favorite movie, a story o...  positive
6   i sure would like to see a resurrection of a u...  positive
7   this show was an amazing, fresh & innovative i...  negative
8   encouraged by the positive comments about this...  negative
9   if you like original gut wrenching laughter yo...  positive
10  phil the alien is one of those quirky films wh...  negative
11  i saw this movie when i was about 12 when it c...  negative
12  so im not a big fan of boll's work but then ag...  negative
13  the cast played shakespeare.shakespeare lost.i...  negative
14  this a fantastic movie of three prisoners who ...  positive
15  kind of drawn in by the erotic scenes, only to...  negative
16  some films just simply should not be remade. t...  positive
17  this movie made it into one of my top 10 most ...  negative
18  i remember this film,it was the first film i h...  positive
19  an awful film it must have been up against som...  negative
20  after the success of die hard and it's sequels...  positive
21  i had the terrible misfortune of having to vie...  negative
22  what an absolutely stunning movie, if you have...  positive
23  first of all, let's get a few things straight ...  negative
24  this was the worst movie i saw at worldfest an...  negative
25  the karen carpenter story shows a little more ...  positive
26  "the cell" is an exotic masterpiece, a dizzyin...  positive
27  this film tried to be too many things all at o...  negative
28  this movie was so frustrating. everything seem...  negative
29  war movie' is a hollywood genre that has been ...  positive
30  taut and organically gripping, edward dmytryk'...  positive
31  "ardh satya" is one of the finest film ever ma...  positive
32  my first exposure to the templarios & not a go...  negative
33  one of the most significant quotes from the en...  positive
34  i watched this film not really expecting much,...  negative
35  i bought this film at blockbuster for $3.00, b...  negative
36  the plot is about the death of little children...  negative
37  ever watched a movie that lost the plot? well,...  negative
38  okay, so this series kind of takes the route o...  positive
39  after sitting through this pile of dung, my hu...  negative
40  it had all the clichés of movies of this type ...  negative
41  this movie is based on the book, "a many splen...  positive
42  of all the films i have seen, this one, the ra...  negative
43  i had heard good things about "states of grace...  negative
44  this movie struck home for me. being 29, i rem...  positive
45  as a disclaimer, i've seen the movie 5-6 times...  positive
46  protocol is an implausible movie whose only sa...  negative
47  how this film could be classified as drama, i ...  negative
48  preston sturgis' the power and the glory was u...  positive
49  average (and surprisingly tame) fulci giallo w...  negative

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['review']).toarray()

array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.084815, ..., 0.      , 0.      , 0.      ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[4.23867845 4.23867845 2.73460106 ... 4.23867845 4.23867845 4.23867845]
['00' '000' '10' ... 'zellweger' 'zombie' 'zwick']